description: "openDANES is a platform for tutorials and white papers about using computational methodologies for ancient Near Eastern studies"
email: "digpasts@gmail.com"
twitter: "https://twitter.com/DigPastsLab"
twitter-handle: "@DigPastsLab"
webname: "openDANES"
BEn-old: "https://babylonian.herokuapp.com/#/"
BEn-new: "https://ben-digpasts.com/"
BEn-new-demo: "https://ben-digpasts.com/demo"
github: "https://github.com/DigitalPasts"
dig-pasts: "https://digitalpasts.github.io/index.html"
url: "https://digitalpasts.github.io"
baseurl: "/openDANES"
tutorials: "https://digitalpasts.github.io/openDANES/tutorials"